USE WEBFLIX;
INSERT INTO category (name) VALUES
('Action'), 
('Animation'), 
('Arts Martiaux'), 
('Aventure'),
('Biopic'),
('Bollywood'),
('Comédie'), 
('Comédie dramatique'), 
('Divers'),
('Documentaire'),
('Drame'),
('Epouvante-horreur'),
('Erotique'),
('Espionnage'), 
('Famille'),
('Fantastique'),
('Guerre'), 
('Historique'), 
('Musical'),
('Policier'), 
('Romance'), 
('Science fiction'), 
('Thriller'), 
('Western');